In [1]:
import numpy as np

In [2]:
# matrix multiplication
a = np.array([[0,6],[2,8],[4,10]])
b = np.array([[1,3,5],[7,9,11]])
print(a)
print(b)
print(np.dot(a,b))

[[ 0  6]
 [ 2  8]
 [ 4 10]]
[[ 1  3  5]
 [ 7  9 11]]
[[ 42  54  66]
 [ 58  78  98]
 [ 74 102 130]]


In [3]:
print(np.matmul(a,b))

[[ 42  54  66]
 [ 58  78  98]
 [ 74 102 130]]


In [4]:
# sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [5]:
x1=1
x2=1
score = 4*x1 + 5*x2 - 9

In [6]:
sigmoid(score)

0.5

In [7]:
w1=3
w2=5
b=-2.2

sigmoid(w1*0.4 + w2*0.6 + b)

0.8807970779778823

In [8]:
# eigenvector and eigenvalues
A = np.array([[3, 0],[-9, 6]])
x = np.array([1, 3])

np.dot(A, x)

array([3, 9])

In [ ]:
# picture size calculation
# [(W−K+2P)/S]+1
#     W  = input volume
#     K  = Kernel size (dimensions)
#     P =  padding
#     S = stride (step lenght)

(130-3+0)/1+1