In [1]:
import numpy as np

In [2]:
# matrix multiplication
a = np.array([[0,6],[2,8],[4,10]])
b = np.array([[1,3,5],[7,9,11]])
print(a)
print(b)
print(np.dot(a,b))

[[ 0  6]
 [ 2  8]
 [ 4 10]]
[[ 1  3  5]
 [ 7  9 11]]
[[ 42  54  66]
 [ 58  78  98]
 [ 74 102 130]]


In [3]:
print(np.matmul(a,b))

[[ 42  54  66]
 [ 58  78  98]
 [ 74 102 130]]


In [4]:
# sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [5]:
x1=1
x2=1
score = 4*x1 + 5*x2 - 9

In [6]:
sigmoid(score)

0.5

In [7]:
w1=3
w2=5
b=-2.2

sigmoid(w1*0.4 + w2*0.6 + b)

0.8807970779778823

In [8]:
# eigenvector and eigenvalues
A = np.array([[3, 0],[-9, 6]])
x = np.array([1, 3])

np.dot(A, x)

array([3, 9])

In [9]:
# picture size calculation
#     W  = input volume
#     K  = Kernel size
#     P =  padding
#     S = stride

np.int_(((130-3+0)/1)+1)

128

$[(W−K+2*P)/S]+1$

In [10]:
# calculating padding that has kernel_size of 7 for CNN that is the same x-y size as an input array
# see above equation; using P = 3
x = (-7 + 2*3/1) + 1 # results in zero; W - 0 = W
print(np.int_(x))

0


In [11]:
from sympy import Symbol

Symbol('w') + x == Symbol('w') # W = W; CNN has same x-y size as input array

True

In [12]:
# nlp: Subsampling equation
# text with 1 million words in it
# word "learn" appears 700 times in this text
# threshold is 0.0001

$p = 1 - \sqrt{\frac{t}{f(x_[i])}}$

In [13]:
# -> calculate probability that we will discard the word "learn"
f = 700
w_i = 1e6
t = 1e-4

In [14]:
p = 1 - np.sqrt(t/(f/w_i))
print(p)

0.6220355269907727


In [15]:
# For an input [23, 702, 89, 15, 99] and R=2, what will the returned context be if we pass in the token at idx=1 (702)?
def get_target(words, idx, R):
    start = idx - R if (idx - R) > 0 else 0
    stop = idx + R
    target_words = words[start:idx] + words[idx+1:stop+1]
    
    return list(target_words)

In [16]:
print(get_target(words=[23, 702, 89, 15, 99], idx=1, R=2))

[23, 89, 15]
